# Site settings
title: My Insert-Blog-Title-Here Blog
email: damewood@physics.ucdavis.edu
description: > # this means to ignore newlines until "baseurl:"
  Some random stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ldamewood.github.io" # the base hostname & protocol for your site
twitter_username: ldamewood
github_username: ldamewood

# Build settings
markdown: kramdown
